### ISSUE TITLE
Embed labels removed

### ISSUE THREAD

**Issue by igorakkerman** [dy-sh/obsidian-consistent-attachments-and-links#110]
With the latest update (I'm on 3.13.3), the "labels" of embeds are removed:
```markdown
![Target](Target.md)
```
becomes
```markdown
![](Target.md)
```
It's not an issue immediately but when I remove the `!` to turn the embed into a link, the link has no label. I noticed that the label is brought back when the note is reloaded but I'd prefer it not to be removed in the first place.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.14.0

**Comment by igorakkerman** [comment]
@mnaoumov Thank you so much for working on the issue. Unfortunately, the problem remains in 3.14.0. Looking at your latest commits, I can't see any code changes, apart from linting and library updates.

**Comment by mnaoumov** [comment]
@igorakkerman yes, updating library supposed to help.

As you claim it isn't, I need more details. Please prepare a test vault and record a video proving the issue is still there.

**Comment by igorakkerman** [comment]
@mnaoumov before and after re-installing the plugin and running a full update, I made a backup. Below's an example diff.
Please let me know if that helps or I should create another vault.
![image](https://github.com/user-attachments/assets/2bdf70de-0bf5-46d0-92e6-3fd87489eee1)

**Comment by igorakkerman** [comment]
@mnaoumov *Reorganize Vault*, I use a shortcut for it.
![image](https://github.com/user-attachments/assets/6b91c2aa-203d-4f94-8751-40b941c8601d)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.19.0

**Comment by igorakkerman** [comment]
Thanks so much, @mnaoumov! Seems to work perfectly now.
